# secrets.GITHUB_TOKEN 在 push 和 release 時都需要相應權限，需確認 Repo 的 Settings > Actions > General > Workflow permissions 是 Read and write

name: Sync All Tools to Release

on:
  # workflow_run=>監聽其他workflows
  workflow_run:
    # workflows=>定義監聽目標，對應 NugetPublish.yml 的 name
    workflows: ["NuGet Publish"]
    # types=>定義觸發條件
    types:
      - completed
  # workflow_dispatch=>保留手動觸發功能
  workflow_dispatch:

jobs:
  sync-release:
    # 只有當前一個 workflow 執行成功時才跑
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    # 指定執行所在的作業系統環境為 Windows 的最新版本
    runs-on: windows-latest
    
    # 所有步驟邏輯集中於 Shell/CICD.ps1
    defaults:
      run:
        shell: pwsh

    steps:
      # 將 Git 儲存庫的程式碼拉取到執行環境中
      - name: Checkout
        uses: actions/checkout@v4

      # 讀取同資料夾下的設定檔
      - name: Load environment variables
        run: ./Shell/CICD.ps1 -Command ImportEnvFile -EnvFile .github/workflows/public.env

      # 建立時間戳記供 Release 使用
      - name: Generate Timestamp
        run: ./Shell/CICD.ps1 -Command GenerateTimestamp

      # 循環下載所有專案的最新版
      - name: Download All Latest Packages
        run: ./Shell/CICD.ps1 -Command DownloadLatestPackages `
          -IncludeProjects "$env:INCLUDE_PROJECTS" `
          -GitHubToken "${{ secrets.GITHUB_TOKEN }}" `
          -GitHubActor "${{ github.actor }}" `
          -NugetSource "$env:GITHUB_NUGET_SOURCE" `
          -OutputDir "./release_assets"

      # 3. 更新 GitHub Release
      - name: Update GitHub Release Assets
        run: ./Shell/CICD.ps1 -Command UpdateReleaseAssets `
          -GitHubToken "${{ secrets.GITHUB_TOKEN }}" `
          -ReleaseRepo "${{ github.repository }}" `
          -ReleaseTag "latest-tools" `
          -ReleaseTitle "Latest Tools Nupkg" `
          -ReleaseTime "$env:RELEASE_TIME" `
          -OutputDir "./release_assets"